### ISSUE TITLE
Masang apikey

### ISSUE THREAD

**Issue by PencintaSenja** [Arya274/Arya-BOT4#4]
Cara masang apikeynya gimana?

**Comment by Alfat537** [comment]
Kamu pake termux / PC?

**Comment by Bintangp02** [comment]
Tinggal lewat Termux Atau Pc dan Leptop??

**Comment by PencintaSenja** [comment]
Dual ngab

**Comment by JereGanz342** [comment]
Caea masang apikey ya gmna gitu buat sendiri lah jgn manja
